// Demo library data with playlists, albums, and metadata for a realistic library view

const demoTracks: LibraryTrack[] = [
  {
    id: "dQw4w9WgXcQ",
    title: "Rick Astley - Never Gonna Give You Up",
    channel: "Rick Astley",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
    duration: 213,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 7,
    metadata: { artist: "Rick Astley", cleanTitle: "Never Gonna Give You Up", album: "Whenever You Need Somebody", year: 1987, genre: "Pop" },
  },
  {
    id: "fJ9rUzIMcZQ",
    title: "Queen - Bohemian Rhapsody",
    channel: "Queen Official",
    thumbnail: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/mqdefault.jpg",
    duration: 354,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 6,
    metadata: { artist: "Queen", cleanTitle: "Bohemian Rhapsody", album: "A Night at the Opera", year: 1975, genre: "Rock" },
  },
  {
    id: "hTWKbfoikeg",
    title: "Nirvana - Smells Like Teen Spirit",
    channel: "Nirvana",
    thumbnail: "https://i.ytimg.com/vi/hTWKbfoikeg/mqdefault.jpg",
    duration: 301,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 5,
    metadata: { artist: "Nirvana", cleanTitle: "Smells Like Teen Spirit", album: "Nevermind", year: 1991, genre: "Grunge" },
  },
  {
    id: "YQHsXMglC9A",
    title: "Adele - Hello",
    channel: "Adele",
    thumbnail: "https://i.ytimg.com/vi/YQHsXMglC9A/mqdefault.jpg",
    duration: 367,
    downloaded: false,
    addedAt: Date.now() - 86400000 * 4,
    metadata: { artist: "Adele", cleanTitle: "Hello", album: "25", year: 2015, genre: "Pop" },
  },
  {
    id: "kJQP7kiw5Fk",
    title: "Luis Fonsi - Despacito ft. Daddy Yankee",
    channel: "Luis Fonsi",
    thumbnail: "https://i.ytimg.com/vi/kJQP7kiw5Fk/mqdefault.jpg",
    duration: 282,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 3,
    metadata: { artist: "Luis Fonsi", cleanTitle: "Despacito", album: "Vida", year: 2017, genre: "Latin Pop" },
  },
  {
    id: "JGwWNGJdvx8",
    title: "Ed Sheeran - Shape of You",
    channel: "Ed Sheeran",
    thumbnail: "https://i.ytimg.com/vi/JGwWNGJdvx8/mqdefault.jpg",
    duration: 263,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 2,
    metadata: { artist: "Ed Sheeran", cleanTitle: "Shape of You", album: "Divide", year: 2017, genre: "Pop" },
  },
  {
    id: "RgKAFK5djSk",
    title: "Wiz Khalifa - See You Again ft. Charlie Puth",
    channel: "Wiz Khalifa",
    thumbnail: "https://i.ytimg.com/vi/RgKAFK5djSk/mqdefault.jpg",
    duration: 237,
    downloaded: false,
    addedAt: Date.now() - 86400000 * 1,
    metadata: { artist: "Wiz Khalifa", cleanTitle: "See You Again", year: 2015, genre: "Hip Hop" },
  },
  {
    id: "OPf0YbXqDm0",
    title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
    channel: "Mark Ronson",
    thumbnail: "https://i.ytimg.com/vi/OPf0YbXqDm0/mqdefault.jpg",
    duration: 271,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 0.5,
    metadata: { artist: "Mark Ronson ft. Bruno Mars", cleanTitle: "Uptown Funk", album: "Uptown Special", year: 2014, genre: "Funk" },
  },
  {
    id: "CevxZvSJLk8",
    title: "Katy Perry - Roar",
    channel: "Katy Perry",
    thumbnail: "https://i.ytimg.com/vi/CevxZvSJLk8/mqdefault.jpg",
    duration: 263,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 0.3,
    metadata: { artist: "Katy Perry", cleanTitle: "Roar", album: "Prism", year: 2013, genre: "Pop" },
  },
  {
    id: "09R8_2nJtjg",
    title: "Maroon 5 - Sugar",
    channel: "Maroon 5",
    thumbnail: "https://i.ytimg.com/vi/09R8_2nJtjg/mqdefault.jpg",
    duration: 310,
    downloaded: true,
    addedAt: Date.now() - 86400000 * 0.1,
    metadata: { artist: "Maroon 5", cleanTitle: "Sugar", album: "V", year: 2014, genre: "Pop" },
  },
];

const demoPlaylists: LibraryPlaylist[] = [
  {
    playlistId: "pl-classics",
    title: "Classic Hits",
    thumbnail: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/mqdefault.jpg",
    trackIds: ["dQw4w9WgXcQ", "fJ9rUzIMcZQ", "hTWKbfoikeg"],
    addedAt: Date.now() - 86400000 * 5,
  },
  {
    playlistId: "pl-modern",
    title: "Modern Pop",
    thumbnail: "https://i.ytimg.com/vi/JGwWNGJdvx8/mqdefault.jpg",
    trackIds: ["YQHsXMglC9A", "kJQP7kiw5Fk", "JGwWNGJdvx8", "CevxZvSJLk8", "09R8_2nJtjg"],
    addedAt: Date.now() - 86400000 * 2,
  },
];

export const demoLibrary: LibraryData = {
  tracks: demoTracks,
  playlists: demoPlaylists,
};
